#!/bin/bash
venv/bin/python -m pip install --upgrade build
venv/bin/python -m build
for FILE in dist/*.tar.gz; do
  TXT_FILENAME="dist/$(basename $FILE .tar.gz).txt"
  base64 $FILE > $TXT_FILENAME
done